약간의 정리와 type hint 추가를 진행했습니다.
vEduardovich/dodari pull request #3
Opened 2024-04-17 15:03 UTC by Liberatedwinner

안녕하세요,

약간의 가로폭 정리, 그리고 type hint 추가를 진행했습니다.
제가 HTML 코드는 어떻게 가로를 줄일지 몰라서 우선은 그냥 두었고,
다른 부분의 코드들은 개행을 통해 가로폭을 줄였습니다.

현재 f-string과 .format의 사용이 병행되고 있는 부분은
제가 건드려보기 이전에 여쭈어 본 다음 진행하고자 두었습니다.

살펴봐주시고, 혹여 괜찮으시면 merge를 부탁드립니다.

감사합니다.

2024-04-17 16:37 UTC, vEduardovich commented
와. 제가 파이썬이 부족해서 걱정했었는데 이렇게 힘을 주시니 너무나 감사합니다.
지금은 제 작업 컴퓨터가 사무실에 있어 merge가 어려우니 내일 작업 진행하겠습니다!

2024-04-18 03:48 UTC, vEduardovich requested changes
덕분에 많이 배웠습니다. 
혹시 코멘트 덧붙인 부분도 수정이 가능할까요?

2024-04-18 03:48 UTC, vEduardovich commented on dodari.py
> +            self.selected_files = list(files)
코드가 깔끔하고 readable 해졌어요.
아주 작은 ux경험이긴 한데 self.selected_files = list(files) 에서 list로 감쌀경우
<img width="500" alt="image" src="https://github.com/vEduardovich/dodari/assets/20391482/6b003deb-3891-4951-801b-7ad1d8d2a4ca">
이런 메시지가 나오게 돼요. 이런건 작지만 고객의 ux를 나쁘게 할수도 있어요.
수정을 부탁드려도 될까요?

2024-04-18 04:09 UTC, Liberatedwinner commented on dodari.py
> +            self.selected_files = list(files)
그럼요, 물론입니다.

기존에 `self.selected_files = []`로 초기 선언되어있던 것으로 기억해서,
함수에서는 `Sequence` type으로 받되,  나중에 `list`로 바꾸는 것으로 하려는 의도였지만...
역효과가 나는 것은 저도 바라지 않기에 다시 roll-back했습니다.

괜찮으시면 다시금 확인을 부탁드립니다.

2024-04-18 04:17 UTC, merged